// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGeLEeMfeEoWnXoWlgYRCwJgxsdBQCiJM',
    appId: '1:1097590796154:web:b7ca3fdde338aa5775b0c3',
    messagingSenderId: '1097590796154',
    projectId: 'bloodproject-c77de',
    authDomain: 'bloodproject-c77de.firebaseapp.com',
    storageBucket: 'bloodproject-c77de.appspot.com',
    measurementId: 'G-03Z2591363',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxLmmtQHndHHP4cTj3kDVBoUzLPByUveo',
    appId: '1:1097590796154:android:636d9acc64b21eb175b0c3',
    messagingSenderId: '1097590796154',
    projectId: 'bloodproject-c77de',
    storageBucket: 'bloodproject-c77de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBzpn3OagjtkMhAoroAXyXvxTtow4Ge5E',
    appId: '1:1097590796154:ios:f1eab03f9f1acfb575b0c3',
    messagingSenderId: '1097590796154',
    projectId: 'bloodproject-c77de',
    storageBucket: 'bloodproject-c77de.appspot.com',
    iosBundleId: 'com.example.sampleProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBzpn3OagjtkMhAoroAXyXvxTtow4Ge5E',
    appId: '1:1097590796154:ios:8b656554d93be9a675b0c3',
    messagingSenderId: '1097590796154',
    projectId: 'bloodproject-c77de',
    storageBucket: 'bloodproject-c77de.appspot.com',
    iosBundleId: 'com.example.sampleProject.RunnerTests',
  );
}
